default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: family_album_development
test:
  <<: *default
  database: family_album_test
production:
  <<: *default
  database: family_album_production
  username: family_album
  password: <%= ENV["FAMILY_ALBUM_DATABASE_PASSWORD"] %>
